### ISSUE TITLE
启动时提示“SyntaxError: invalid syntax”

### ISSUE THREAD

**Issue by playcmd** [ssttkkl/nonebot-plugin-pixivbot#1]
```
01-16 18:41:11 [ERROR] nonebot | Failed to import "nonebot-plugin-pixivbot"                                                                                                                                 
Traceback (most recent call last):                                                                                                                                                                          
  File "bot.py", line 27, in <module>                                                                                                                                                                       
    nonebot.load_from_toml("pyproject.toml")                                                                                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/__init__.py", line 1089, in load_from_toml                                                                                                    
    return load_all_plugins(set(plugins), set(plugin_dirs))                                                                                                                                                 
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/__init__.py", line 1031, in load_all_plugins                                                                                                  
    result = context.run(_load_plugin, manager, plugin_name)                                                                                                                                                
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/__init__.py", line 953, in _load_plugin                                                                                                       
    module = manager.load_plugin(plugin_name)                                                                                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin                                                                                                         
    return importlib.import_module(f"{self.namespace}.{name}")                                                                                                                                              
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                                                                               
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                             
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                                                                           
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                                                                
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module                                                                                                         
    super().exec_module(module)                                                                                                                                                                             
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module                                                                                                                                   
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                                                              
  File "/root/Nonebot/src/plugins/nonebot-plugin-pixivbot/__init__.py", line 9, in <module>                                                                                                                 
    from . import common_command                                                                                                                                                                            
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                                                                
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module                                                                                                         
    super().exec_module(module)                                                                                                                                                                             
  File "/root/Nonebot/src/plugins/nonebot-plugin-pixivbot/common_command.py", line 11, in <module>                                                                                                          
    from .distributor import distributor                                                                                                                                                                    
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                                                                
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module                                                                                                         
    super().exec_module(module)                                                                            
  File "/root/Nonebot/src/plugins/nonebot-plugin-pixivbot/distributor.py", line 15, in <module>                                                                                                             
    from .data_source import PixivDataSource, pixiv_data_source, pixiv_bindings                                                                                                                             
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                                                                
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module                                                                                                         
    super().exec_module(module)                                                                                                                                                                             
  File "/root/Nonebot/src/plugins/nonebot-plugin-pixivbot/data_source/__init__.py", line 1, in <module>                                                                                                     
    from .pixiv_data_source import PixivDataSource, pixiv_data_source                                                                                                                                       
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                                                                
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module                                                                                                         
    super().exec_module(module)                                                                                                                                                                             
  File "/root/Nonebot/src/plugins/nonebot-plugin-pixivbot/data_source/pixiv_data_source.py", line 394                                                                                                       
    @get_driver().on_startup                                                                                                                                                                                
                 ^                                                                                                                                                                                          
SyntaxError: invalid syntax
```
环境Docker+Debian+Python3

**Comment by ssttkkl** [comment]
使用python3.9及以上的版本
