### ISSUE TITLE
KeyError: <class 'apscheduler.schedulers.asyncio.AsyncIOScheduler'>

### ISSUE THREAD

**Issue by ANGJustinl** [ssttkkl/nonebot-plugin-pixivbot#110]
##报错如下

########

12-24 08:13:23 [SUCCESS] nonebot | OneBot V11 2715252422 | [message.group.normal]: Message 245639597 from 77139032@[群:7
37521032] "看看榜"
12-24 08:13:23 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_pixivbot.handler.
common.ranking)
12-24 08:13:23 [INFO] nonebot_plugin_pixivbot | [mediator] illust_ranking day cache_strategy=NORMAL
12-24 08:13:24 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.ranking) running c
omplete
12-24 08:13:24 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.ranking)
failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in _
_call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in m
ain
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in i
nvoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in i
nvoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in in
voke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line
30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", lin
e 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273,
 in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", li
ne 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in
run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in
 run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_unt
il_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_
forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_for
ever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_o
nce
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 142,
in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 188,
in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matche
r.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matche
r.py", line 702, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.p
y", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\common\ranking.py", line 58, in on_match
    await self.handle(mode, num, post_dest=post_dest)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\base.py", line 80, in handle
    await self.interceptor.intercept(self._parse_args_and_actual_handle, *args,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\interceptor\combined_interceptor.py", line 45, in intercept
    await self.x.intercept(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\interceptor\combined_interceptor.py", line 45, in intercept
    await self.x.intercept(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\interceptor\combined_interceptor.py", line 45, in intercept
    await self.x.intercept(
  [Previous line repeated 2 more times]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\interceptor\default_error_interceptor.py", line 36, in intercept
    raise e  # 重新抛出，让上层可以处理（如scheduler中需要处理Handler的异常）
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\interceptor\default_error_interceptor.py", line 22, in intercept
    await wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\interceptor\permission_interceptor.py", line 34, in intercept
    await wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\interceptor\permission_interceptor.py", line 34, in intercept
    await wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\interceptor\timeout_interceptor.py", line 21, in intercept
    await wait_for(wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\interceptor\loading_prompt_interceptor.py", line 33, in intercept
    await wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\interceptor\permission_interceptor.py", line 34, in intercept
    await wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\base.py", line 111, in _parse_args_and_actual_handle
    await self.actual_handle(post_dest=post_dest, silently=silently, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\handler
\common\ranking.py", line 115, in actual_handle
    illusts = await self.service.illust_ranking(mode, range)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\service
\pixiv_service.py", line 40, in illust_ranking
    async for x in self.repo.illust_ranking(mode):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\data\pi
xiv_repo\mediator_repo.py", line 368, in illust_ranking
    async with self._shared_agen_mgr.get(SharedAgenIdentifier(PixivResType.ILLUST_RANKING, mode=mode),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\utils\s
hared_agen.py", line 193, in get
    origin = self.agen(identifier, cache_strategy, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\data\pi
xiv_repo\mediator_repo.py", line 177, in agen
    return self.factories[identifier.type](self, cache_strategy=cache_strategy, **merged_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\data\pi
xiv_repo\mediator_repo.py", line 140, in illust_ranking_factory
    cache_factory=self.local.illust_ranking,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\context
.py", line 16, in __get__
    return context.require(self._key)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\context
.py", line 136, in require
    return self._find_provider(key).provide()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\context
.py", line 46, in provide
    self._cache = self._func()  # just let it throw
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\context
.py", line 90, in <lambda>
    self.register_lazy(cls, lambda: cls(*args, **kwargs))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\data\pi
xiv_repo\local_repo\sql.py", line 53, in __init__
    self.apscheduler.add_job,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\context
.py", line 16, in __get__
    return context.require(self._key)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\context
.py", line 136, in require
    return self._find_provider(key).provide()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\context
.py", line 144, in _find_provider
    raise KeyError(key)
KeyError: <class 'apscheduler.schedulers.asyncio.AsyncIOScheduler'>

##########

配置如下
![image](https://user-images.githubusercontent.com/96008766/209414883-9b477e97-e39e-4cab-b691-b4171ed606f2.png)

##########

我已经配置好代理，并用代理成功获取了refresh_token并填入，但使用command便会报错
![image](https://user-images.githubusercontent.com/96008766/209414922-310968d4-fc1e-4788-899e-67bebc4afd72.png)
![image](https://user-images.githubusercontent.com/96008766/209414986-c4bb1e48-9d59-40e2-b1d1-bd526161d209.png)

**Comment by ANGJustinl** [comment]
![image](https://user-images.githubusercontent.com/96008766/209415003-29c85d58-daf5-401d-91a1-0d686492ece0.png)
![image](https://user-images.githubusercontent.com/96008766/209415012-b692c7ef-e5b7-4435-8f2f-df17a5f9a422.png)
![image](https://user-images.githubusercontent.com/96008766/209415021-59b4269e-4ea2-4c84-a3a0-c07ea8a228d2.png)
![image](https://user-images.githubusercontent.com/96008766/209415029-1e174ec6-7b7d-4c4b-b0f5-14bb8ecdbc30.png)

**Comment by ssttkkl** [comment]
升级下nonebot-plugin-apscheduler试试

**Comment by ANGJustinl** [comment]
不行
我pip install -U 和--upgrade都试了还是同样的报错

**Comment by ANGJustinl** [comment]
我觉得是代理配置的问题，大佬您有没有pivix_proxy这个配置的例子，我应该是代理配置的不对

**Comment by ssttkkl** [comment]
> 我觉得是代理配置的问题，大佬您有没有pivix_proxy这个配置的例子，我应该是代理配置的不对

代理应该是socks5://127.0.0.1:1080

但是我不知道和这个有没有关系，你先试试吧

**Comment by ssttkkl** [comment]
还有refresh_token码一下，通过这个token可以直接上你的p站号

**Comment by ANGJustinl** [comment]
好的谢谢提醒:D
我代理确实写的不对，我写的'socks5':'XXXX'
