### ISSUE TITLE
设置refresh_token后仍然无法启动

### ISSUE THREAD

**Issue by SherkeyXD** [ssttkkl/nonebot-plugin-pixivbot#164]
如题，refresh_token就是在服务器上用gppt获取的，应该不是网络问题
log:
> Traceback (most recent call last):
  File "/home/ubuntu/Bot/MizukiBot-Lazer/bot.py", line 36, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot_plugin_pixivbot/__init__.py", line 10, in <module>
    from .handler.command.help import help_text
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot_plugin_pixivbot/handler/__init__.py", line 1, in <module>
    from . import command
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot_plugin_pixivbot/handler/command/__init__.py", line 1, in <module>
    from .bind import BindHandler, UnbindHandler
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot_plugin_pixivbot/handler/command/bind.py", line 4, in <module>
    from nonebot_plugin_pixivbot.service.pixiv_account_binder import PixivAccountBinder
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot_plugin_pixivbot/service/__init__.py", line 1, in <module>
    from . import scheduler
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot_plugin_pixivbot/service/scheduler.py", line 12, in <module>
    from nonebot_plugin_pixivbot.data.subscription import SubscriptionRepo
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot_plugin_pixivbot/data/__init__.py", line 5, in <module>
    conf = context.require(Config)
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot_plugin_pixivbot/context.py", line 136, in require
    return self._find_provider(key).provide()
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot_plugin_pixivbot/context.py", line 46, in provide
    self._cache = self._func()  # just let it throw
  File "/home/ubuntu/.pyenv/versions/MizukiBot-Lazer/lib/python3.10/site-packages/nonebot_plugin_pixivbot/context.py", line 90, in <lambda>
    self.register_lazy(cls, lambda: cls(*args, **kwargs))
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
    super().__init__(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Config
pixiv_query_expires_in
  value is not a valid integer (type=type_error.integer)

**Comment by ssttkkl** [comment]
我的意思是你不需要把所有项都复制进去，只将你需要修改成和默认值不一样的项加进去就行

**Comment by ssttkkl** [comment]
你把pixiv_query_expires_in这一项删掉就可以了，或者把所有项都删掉只留一个pixiv_refresh_token肯定是可以的
