### ISSUE TITLE
在未安装特化插件时显示更友好的异常信息

### ISSUE THREAD

**Issue by lovecpm** [ssttkkl/nonebot-plugin-pixivbot#60]
Traceback (most recent call last):
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\query\ranking.py", line 30, in on_match
    await self.handler.handle(mode, num, post_dest=get_post_dest(bot, event))
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\query\utils.py", line 42, in get_post_dest
    return context.require(PostDestinationFactoryManager).from_event(bot, event)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\protocol_dep\post_dest.py", line 63, in from_event
    return self[get_adapter_name(bot)].from_event(bot, event)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\protocol_dep\protocol_dep.py", line 31, in __getitem__
    return self.require(adapter)
  File "C:\Users\26682\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_pixivbot\protocol_dep\protocol_dep.py", line 28, in require
    return context.require(self.factories[adapter])
KeyError: 'onebot'

**Comment by ssttkkl** [comment]
pip install nonebot-plugin-pixivbot[onebot]试试？
或者pip install nonebot-plugin-pixivbot-onebot-v11
